### PR TITLE
fix: adapt to non-backward-compatible changes in driver library

### PR DESCRIPTION
**Pull request by doudou**
Depends on:
- [ ] https://github.com/tidewise/drivers-gps_ublox/pull/7

* renamed GPSData into PVT
* moved "public" configuration enums to gps_ublox instead of under Driver

### CODE REVIEW

**Review by rodrigoleonello — APPROVED** [review]

**Review by caioaamaral — APPROVED** [review]
LGTM!

**Comment by caioaamaral** [comment]
What does PVT stand for?

**Comment by rodrigoleonello** [comment]
> What does PVT stand for?

I think it is private.

**Comment by doudou** [comment]
> > What does PVT stand for?
> 
> I think it is private.

Position-Velocity-Time. It's the name of the package in the ublox documentation

**Pull request merged**
